### ISSUE TITLE
wrong action, please delete

### ISSUE THREAD

**Issue by xuzh4299** [tholden/dynareOBC#1]

**Comment by tholden** [comment]
The issue opener was running an experiment involving average/expected IRFs, and was not aware that by default DynareOBC tries to incorporate future uncertainty by integrating over future shocks (like default dynare’s IRFs at order 2).

Conditional on being near the bound, other shocks have a positive effect in expectation on interest rates (as they can’t fall father). Thus, with average IRFs, an impulse response will not normally hit the bound.

For a perfect foresight impulse response (which will hit the bound), run “dynareOBC filename.mod nocubature”.
