### ISSUE TITLE
repmat error

### ISSUE THREAD

**Issue by altophohe** [tholden/dynareOBC#11]
Hello. I am currently trying to play with dynareOBC and I got to have one bug-like failure in running my mod file. 

When I try to run my mod file with the ZLB constraint on interest rates (thus, max operator in the code), dynareOBC seemed to work well in the beginning, particularly till feasibility check(S matrix, M matrix etc), but at some moment it totally collapsed and stop working for simulation. The specific message I got is 

Error using repmat
Replication factors must be a row vector of integers or integer scalars.
Error in DoubleDouble/ExpandSingleton (line 1914)
                varargout{ i } = repmat( varargin{ i }, s ./ ss( i, : ) );
Error in DoubleDouble/DDDividedByDD (line 2089)
                [ a1, a2, b1, b2 ] = DoubleDouble.ExpandSingleton( a1, a2, b1, b2 );
Error in DoubleDouble/lu (line 971)
                    [ v.v1( i, k ), v.v2( i, k ) ] = DoubleDouble.DDDividedByDD( v.v1( i, k ), v.v2( i, k ), v.v1( k, k ), v.v2( k, k )
                    );
Error in RobustDeterminantDD (line 14)
    [ L, U, P ] = lu( A );
Error in InitialChecks (line 285)
                    TmpDet = RobustDeterminantDD( Ms( TmpSet, TmpSet ) );
Error in ModelSolution (line 178)
            dynareOBC = InitialChecks( dynareOBC );
Error in dynareOBCCore (line 528)
        [ Info, M_, options_, oo_ , dynareOBC ] = ModelSolution( ( ~dynareOBC.Estimation ) && ( size( FlipsTried, 1 ) == 1 ), M_,
        options_, oo_, dynareOBC );
Error in dynareOBCSetup (line 157)
        dynareOBC_ = dynareOBCCore( InputFileName, basevarargin, dynareOBC_, @() EnforceRequirementsAndGeneratePath( Update,
        OriginalPath, CurrentFolder, dynareOBCPath, InputFileName, varargin{:} ) );
Error in dynareOBC (line 684)
        dynareOBCSetup( OriginalPath, CurrentFolder, dynareOBCPath, InputFileName, varargin{:} ); 

Something like this. 

What I am wondering is that the code goes with dynareOBC very well once I get rid of the max operator. Thus, I don't  think the problem coming from the code itself, but there is something I am missing in dealing with the max operator using dynareOBC.  

I am afraid that the similar problem also occurs when I tried to run any example files provided by T. holden. 

Do you know any potential reason for this and could you give me any advice to fix this issue?

Thanks!

**Comment by altophohe** [comment]
Ah. FYI, I installed the latest release, that is dynareOBC v 3.02 1845 which is uploaded 4 days ago. 
Moreover, I had gone through all advices in the manual, for example removing MAT file, mex file in the core directory, re-instrall etc. So I have no clue why it does not work at this moment.

**Comment by tholden** [comment]
Sorry for the delayed response. What version of MATLAB are you using?

As a work around for this issue, you can run DynareOBC with the `UseVPA` command line option.

However, I would really appreciate if you could help me debug this issue, as I cannot replicate it here. To do this, first place a breakpoint on line 10 of RobustDeterminantDD.m within Core\MChecks. When this breakpoint is hit, add a new breakpoint on line 1914 of DoubleDouble.m within Extern\DoubleDouble. (This line should read `varargout{ i } = repmat( varargin{ i }, s ./ ss( i, : ) );`.). Now continue MATLAB execution (press F5) and it will hit the new breakpoint. Record the value of `varargin`, `s` and `ss` by hovering your mouse over them and noting each of the results, then press F5 to continue execution. Repeat this process until you hit the error, and then report the final values of `varargin`, `s` and `ss` to me.

**Comment by altophohe** [comment]
Sorry for the delayed response. Indeed, I switched to the fully non-linear approximation to deal with OBC, so I couldn't check whether dynareOBC works or not under the above direction you gave. I will try to check and to come back after doing what you asked for. 

Thank you for your help though!
Euiyoung

**Comment by tholden** [comment]
Closing for now due to no response. Reopen if you encounter the issue again.
