### ISSUE TITLE
Estimation error

### ISSUE THREAD

**Issue by wenddymacro** [tholden/dynareOBC#12]
platform： matlab 2017b+dynare 4.5.7

I had run the estimation template in the paper "Jonathan Swarbrick, Tom Holden(2018):Occasionally Binding Constraints in DSGE Models"

error message is :

required MEX is missing！

Thanks in advanced!

**Comment by tholden** [comment]
I don't know what paper you're referring to. In any case, at present the estimation code is not in a state at which I can reasonably recommend that anyone uses it.
