### ISSUE TITLE
About the IRF values of running dynareOBC

### ISSUE THREAD

**Issue by bian-sdufe** [tholden/dynareOBC#13]
Dear Holden,
Thanks for your contribution of the dynareOBC tollbox. I have two questions on the IRFs reported by dynareOBC.
The first is that IRFs reported by running "dynareOBC filename.mod" are very different from the IRFs obtained by running ""dynareOBC filename.mod IRFsAroundZero". Which can be seen as the "real" responses of endogenous variables?
The second question is that after running mod file with "IRFsAroundZero", IRF values of the norminal interest rate are always less than zero, which violates the constraint of "i >= 0". How to understand this?
mod files cannot be attached here, so I have also sent you a message in dynare forum (https://forum.dynare.org/u/cfp), which describes my puzzles in details, and two related files are attached.
Would you please answer the message (or here directly)? Thank you.

**Comment by tholden** [comment]
IRFsaroundzero are relative to the steady state. So zero means the variable is at steady-state, and the ZLB will be negative, as it's below steady state.
The IRFsaroundzero IRFs are identical to the ones without this option, up to a constant which shifts them up or down.

**Comment by bian-sdufe** [comment]
Thank you for the reply, Prof. Holden. I understand the difference between the two sets of IRFs now.
