### ISSUE TITLE
Incorrect processing of files with variable name tags e.g. "(long_name='consumption')"

### ISSUE THREAD

**Issue by tholden** [tholden/dynareOBC#14]
The combination of the "loglinear" option and variable name tags is failing at present.

As a work around, remove variable name tags if using the loglinear option.

**Comment by frantisekmasek** [comment]
Hello, Mr. Holden. The above-mentioned issue is the one that I noted about it at the Dynare forum. Thank you for adding it here. If you allow, I would like to ask you another question related to using your OBC and the "loglinear" option. 

When I use the option, there are not shown any graphs of IRFs; however, if I use the same model without the "loglinear" option, everything runs including the graphs. Would you know where could be a problem? 

Thanks a lot in advance.

**Comment by tholden** [comment]
That is not a bug. "Log-linear" is implemented via MLVs. (To see this, run with the "nocleanup" command line option, and look at the generated MOD files.) If you want a plot of the MLVs (i.e. the original variables in levels) then you need to turn on MLV simulation. Alternatively, you could just remove the variable names after your stoch_simul command, and it ought to give you IRFs for the variables in logs. As a general rule, you're always better off manually defining transformed variables with MLVs yourself, rather than using log-linear. Then you can control these things more precisely.
