### ISSUE TITLE
Stochastic simulation + paralelization

### ISSUE THREAD

**Issue by xsukupovak** [tholden/dynareOBC#2]
Hello,

I tried to simulate New Keynesian model with constraint on interest rate with options
dynareOBC model_obc.mod TimeToEscapeBounds=40 nocubature ShockSequenceFile=shocksequence.mat DisplayBoundsSolutionProgres.

Within the .mod file the stoch_simul(periods=80, irf=0) is used

Each time I try to simulate this version of model, I get error:

```
In an assignment  A(I) = B, the number of elements in B and I must be the same.
Error in SolveBoundsProblem (line 66)
            y( CssIndices ) = yScaled;
Error in SimulateModel (line 233)
                        y = `SolveBoundsProblem(` UnconstrainedReturnPath );
Error in RunStochasticSimulation (line 44)
    Simulation = SimulateModel( ShockSequence, true );
Error in dynareOBCCore (line 494)
        [ oo_, dynareOBC ] = RunStochasticSimulation( M_, options_, oo_, dynareOBC );
Error in dynareOBCSetup (line 145)
        dynareOBC_ = dynareOBCCore( InputFileName, basevarargin, dynareOBC_, @()
        EnforceRequirementsAndGeneratePath( Update, OriginalPath, CurrentFolder, dynareOBCPath,
        InputFileName, varargin{:} ) );
Error in dynareOBC (line 122)
        dynareOBCSetup( OriginalPath, CurrentFolder, dynareOBCPath, InputFileName, varargin{:} ); 
```

The wierd thing is, that the same model with multiple bounds (Zero Lower Bound + lower bound on nominal exchange rate) is simulated without problems.

Also, the simulation with multiple constraints won't attempt to call parpool and whole simulation is performed without paralelization. I am really confused, because I am not aware to do anything that could explain the difference.

Thank you for comment.

**Comment by tholden** [comment]
Please can you attach your MOD file?
Parallelisation is never used for nocubature simulation.

**Comment by xsukupovak** [comment]
[model_obc.zip](https://github.com/tholden/dynareOBC/files/297671/model_obc.zip)
It is a model following Alpanda, Kotze, Woglom (2010) . 
model_obc_zlb is the version with one bound, model_obc_zlb_e contains two bounds.
Thank you for advise.

**Comment by tholden** [comment]
Haven't tried your MOD yet, but I think I've fixed the issue in this commit https://github.com/tholden/dynareOBC/commit/8b3d2473631a75ef05b63c008b3c29f77788bfe8 
Did you see a warning immediately before that error? If so, that fits. I imagine the parametric simulation failed for some reason. (A corrupted install of MPT or MinGW say.)

**Comment by tholden** [comment]
If you update (just delete all the .mat files in the DynareOBC directory), it ought to be fixed.

**Comment by tholden** [comment]
Both seem to run fine with my set-up. (Though the _e file seems to result in the solution of a very difficult problem, which causes it to go very slowly around 66%.)

**Comment by xsukupovak** [comment]
Yes, this is correct. I tried to run it on different computer and it was succesful, nevertheless it opened the paralel pool and closed the pool shortly before simulation.

Thank you for your help..
