### ISSUE TITLE
Build error on macOS

### ISSUE THREAD

**Issue by raphaelhuleux** [tholden/dynareOBC#21]
Hello, 

I am trying to run an example file (on capital constraint) on macOS Catalina, but I get the following error:

```
??? Build error: C compiler produced errors. See the Build Log for further details.
More information
Code generation failed: View Error Report
Error using RunGlobalSolution (line 2)
```

I have Xcode11 installed. Any idea how to solve this?

**Comment by tholden** [comment]
Start by looking at the error report! Should make things clear.

**Comment by tholden** [comment]
Closing as no further info provided.
