### ISSUE TITLE
Warning regarding Invalid Mex-file

### ISSUE THREAD

**Issue by anhpham52** [tholden/dynareOBC#23]
<img width="1099" alt="Screen Shot 2020-08-19 at 22 01 36" src="https://user-images.githubusercontent.com/69302326/90689226-98b92200-e267-11ea-90a8-929b0071dbcf.png">

Dear Dr. Holden,

When I run your example SmetsWouters2007, there are warnings stating Name is nonexistent or not a directory. I don't know if this is normal or what should I do to eliminate this. Thank you!

**Comment by tholden** [comment]
Do you have MATLAB Coder installed? Do you have Gurobi or a similar package installed? Have a look at the Getting Started guide in the first section of TheoryPaperAppendices.pdf.

**Comment by anhpham52** [comment]
Yes, I have installed all the necessary tools for DynareOBC including MATLAB Coder, Gurobi, Mosek, etc. After doing some research, I doubt that the problem comes from the latest version of Matlab whose library cannot be read by MacOS. I will attach some links stating the same issue. I also follow some of their guidance for troubleshooting but it never works.

https://forum.dynare.org/t/invalid-mex-file-in-matlab-2017-prerelease-version/6030
https://stackoverflow.com/questions/48458660/library-not-loaded-loader-path-libmex-dylib-in-matlab
https://uk.mathworks.com/matlabcentral/answers/100900-how-to-run-engdemo-cpp-in-mac-10-8-mountain-lion-in-matlab-r2013a

For more information, I am using Matlab_R2020a and MacOS 10.15.

**Comment by tholden** [comment]
I'm afraid I don't have a Mac to test this. @jonswarbrick uses DynareOBC on Mac I think, so may have some insight.

**Comment by tholden** [comment]
Closing as I cannot replicate the issue.
