### ISSUE TITLE
Dynare OBC Simulation Run

### ISSUE THREAD

**Issue by igsabuga** [tholden/dynareOBC#26]
Hi Tom,

I'm running a simulation using OBC and I encountered issues where the simulation gets stuck for a while. The time ticker says the simulation is about to finish in 40 seconds but it hasn't been moving for an hour. Have you encountered this issue before? How should I get around this?

![image](https://user-images.githubusercontent.com/42754471/94109015-41930800-fe38-11ea-9cee-69732616a327.png)

Many thanks,
Ivy

**Comment by tholden** [comment]
Which MILP solver are you using? (I.e. did you install Gurobi or similar?) What is your time to escape bounds? How many constraints are there?

**Comment by igsabuga** [comment]
Hi Tom, 

Thank you for the very prompt reply. Yes, I have Gurobi as a solver. I have 2 constraints but have repeatedly written them in the Dynare equation lines, which in Dynare equations terms the max function appears twice and the min function appears thrice, as shown below: 

![image](https://user-images.githubusercontent.com/42754471/94184899-8486c700-fe9c-11ea-8543-3c6b21f2cf54.png)

![image](https://user-images.githubusercontent.com/42754471/94185034-b5ff9280-fe9c-11ea-9305-d69ee369fc60.png)

 Many thanks,
Ivy

**Comment by tholden** [comment]
Duplicating constraints is a bad idea. Introduce a model local variable or endogenous for each constraint.
You should have as many max/min in your Dynare code as there are constraints.

**Comment by igsabuga** [comment]
Thanks, Tom. I'll do this instead.

**Comment by tholden** [comment]
Closing as seems to be resolved.
