### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by LGhub-t** [tholden/dynareOBC#28]
Hello,

Thank you for the program. I was interested in applying it to the Smets and Wouters models, but I noticed that the SW examples included in the available releases do not run. The corresponding folders also do not include a RunExample.m file.
Is there a way to use these examples, are they available in some other release?

Thank you.

**Comment by tholden** [comment]
The `RunExample.m` scripts were missing due to a bug in release packaging. This is fixed in release https://github.com/tholden/dynareOBC/releases/tag/v3.30.54.1968
