### ISSUE TITLE
Help with IRFs for two simultaneously different shocks (eg government spending shock with an uncertainty shock

### ISSUE THREAD

**Issue by rui-q** [tholden/dynareOBC#31]
Hi Tom, 

I am new to dynareOBC, and I would like to calculate the government multiplier with an uncertainty shock under the ZLB. I have a question that whether the IRFs of an uncertainty shock could be generated by choosing the option SlowIRFs. And I am confused about how to get the IRFs for two simultaneously different shocks (eg government spending shock with an uncertainty shock). Could you please give me some hints or suggestion?  

I would really appreciate your help.

Ray

**Comment by tholden** [comment]
I cannot comment on the uncertainty shock without knowing your model. In general you can get the IRF for two simultaneous shocks by adding a new varexo that enters linearly wherever either of the other two shocks enter.

**Comment by rui-q** [comment]
Thanks for your replying. 

As the model is nonlinear, I am not sure about directly adding a new varexo.
  
I got a simple non-linear NK model with Calvo pricing, simple fiscal rule and ZLB,  and three shocks (government spending shock; the shock for the coefficient of the household consumption and its uncertainty shock). In order to calculate the government spending multiplier,  I want to get the IRFs for the government spending shock and the uncertainty shock for the coefficient of consumption simultaneously. 

Could there be a way that I could directly add two shocks simultaneously before simulation with dynareOBC? 

For example, like generate IRFS for these two shocks simultaneously without the ZLB:

options_.order=3; 
shock_mat_with_zeros=zeros(burnin+IRF_periods,M_.exo_nbr); %shocks set to 0 to simulate without uncertainty
IRF_no_shock_mat = simult_(oo_.dr.ys,oo_.dr,shock_mat_with_zeros,options_.order)'; %simulate series
stochastic_steady_state=IRF_no_shock_mat(1+burnin,:); 

shock_mat = zeros(burnin+IRF_periods,M_.exo_nbr);
shock_mat(1+burnin,strmatch('eg',M_.exo_names,'exact'))=1; (the government spending shock)
shock_mat(1+burnin,strmatch('evolgamma',M_.exo_names,'exact'))= 1; (the uncertainty shock for the coefficient of consumption )
IRF_mat = simult_(oo_.dr.ys,oo_.dr,shock_mat,options_.order)';

IRF_mat_percent_from_SSS = (IRF_mat(1+burnin+1:1+burnin+IRF_periods,:)-IRF_no_shock_mat(1+burnin+1:1+burnin+IRF_periods,:))./repmat(stochastic_steady_state,IRF_periods,1);

Is it possible to do some adjustments in the file of SlowIRFs? 
 
Thanks again, and I really appreciate that you could spend time replying to me. 

Ray

**Comment by tholden** [comment]
The easiest approach is to add the extra shock as I suggested, but to give it a miniscule impact, so you have e.g. ```g=rho_g*g(-1)+sg*eg+1e-8*eExtra;```
```u=rho_u*u(-1)+su*eu+1e-8*eExtra;```
Then run with ShockScale=1e8 to get the IRF to a unit shock. (Since it has been scaled down to almost zero in the MOD it will have no impact on the simulation.)
