### ISSUE TITLE
Cannot recognize solver

### ISSUE THREAD

**Issue by DongjaeLeee** [tholden/dynareOBC#34]
Hello,

I experience some trouble recognizing solvers when I use DynareOBC.
I installed both Gurobi and CPLEX but when I run testsolver, it reports that dynareOBC doesn't find solvers. 
This program worked well with my old computer but I don't know why it doesn't recognize solver.
Do you have any idea about it?

**Comment by tholden** [comment]
I presume your Matlab path has Gurobi on it? If it's not that, then it sounds like a system path issue. Try restarting your PC? Or reinstalling (Gurobi) then restarting?

**Comment by DongjaeLeee** [comment]
Thanks for the comment. 
 I use a backup program for setting up my new computer and it seems that cause problem. 
I reinstalled Gurobi with a new license code and the problem go away.

**Comment by tholden** [comment]
Great. Glad it's sorted!
