### ISSUE TITLE
Discontinuous Piecewise Function

### ISSUE THREAD

**Issue by tao1fan** [tholden/dynareOBC#35]
Dear Holden,

It's my honor to communicate with you! 

Your program is very easy to solve the DSGE model with continuous piecewise functions, such as ZLB.

However, I have a discontinuous piecewise function in my DSGE model, so I would like to know if I can also use this program to solve this model ( maybe use the sign function? ). The function is following,

F(x)=
0 if x<0
(a+x)/(b+x) if x>=0

Any help in this regard would be very helpful to me.

Respectfully yours!

Yifan TAO

**Comment by tholden** [comment]
No it doesn't handle discontinuous functions.

**Comment by tao1fan** [comment]
Thank you! I will look for other methods.
