### ISSUE TITLE
how to simulate data manually 

### ISSUE THREAD

**Issue by lulu-mao** [tholden/dynareOBC#39]
Hi Tom 
In Dyanre, we can collect the matrics called ghx and ghu under the folder oo_.dr.  and use the equation  yt= yt-1*ghx +ghu*ut to simulate data.  after running dynareOBC I tried to collect the matrics called ghx and ghu under folder oo_.dr. to do the simulation manually. but I'm not sure whether these two matrics have occasionally binding constraints. How does dynareOBC choose certain matrics to simulate data?  and which matric and equations  DynareOBC choose to simulate data.  what should I do if I want to simulate data manually? thanks for the help.
best, 
lulu

**Comment by tholden** [comment]
If it was easy to simulate an OBC model "manually", there would be no need for DynareOBC! It's non linear, so obviously there is no linear transition matrix giving the solution.

**Comment by lulu-mao** [comment]
thanks for the reply. is it possible to give dynareOBC certain shocks and let it do the simulation? the shock is ut, same as the ut in the equation yt= yt-1*ghx +ghu*ut.

**Comment by tholden** [comment]
See the description of the `ShockSequenceFile` option in the ReadMe file.
