### ISSUE TITLE
StochasticSimulation print error

### ISSUE THREAD

**Issue by Lauroc** [tholden/dynareOBC#4]
Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.
Error in TimedProgressBar/updateFile (line 190)
            fprintf(f, '1\n');
Error in TimedProgressBar/progress (line 90)
            obj.updateFile();
Error in SimulateModel (line 268)
                    p.progress;
Error in RunStochasticSimulation (line 52)
        Simulation = SimulateModel( ShockSequence, true );
Error in dynareOBCCore (line 514)
            [ oo_, dynareOBC ] = RunStochasticSimulation( M_, options_, oo_, dynareOBC );
Error in dynareOBCSetup (line 160)
        dynareOBC_ = dynareOBCCore( InputFileName, basevarargin, dynareOBC_, @() EnforceRequirementsAndGeneratePath( Update, OriginalPath,
        CurrentFolder, dynareOBCPath, InputFileName, varargin{:} ) );
Error in dynareOBC (line 627)
        dynareOBCSetup( OriginalPath, CurrentFolder, dynareOBCPath, InputFileName, varargin{:} );
Error in analysis_ (line 9)
dynareOBC BasicModel3 TimeToEscapeBounds=100 shockscale=1 UseVPA PTest=1 compilesimulationcode

**Comment by tholden** [comment]
Do you have full write access in the folder you are working in? Place a break point in TimedProgressBar and see exactly where it was trying to write.

**Comment by Lauroc** [comment]
Hi,
the folder where dynareOBC was installed was "read only". Now that I changed that setting the problem disappeared.
