### ISSUE TITLE
 how to find simul file after using simul_replic 

### ISSUE THREAD

**Issue by Xavia7** [tholden/dynareOBC#40]
Hi tholden,

 I'm using stoch_simul(periods=1000,noprint,order=1,irf=0,simul_replic=1000); and tried to collect 1000 sets of simulated series in DyareOBC, but I can’t find the simulation file.  it should be saved in binary form to the file FILENAME_simul, if it shares the same save path with Dynare. do you know where I can find it?  or am I using the right code to generate 1000 sets of simulated series？ thank you.

**Comment by tholden** [comment]
I'm pretty sure I don't support simul_replic though honestly I don't remember.
Just simulate 1000*1000 periods. The result will be stored in oo_.endo_simul as standard.

**Comment by Xavia7** [comment]
Thank you for your prompt reply. Do you mean simulate 1000*1000 periods once using like stoch_simul(periods=1000*1000,noprint,order=1,irf=0); ?  I just tried in this way, it only produces one set of simulations not 1000.  which code should I use to simulate 1000*1000 periods?

**Comment by tholden** [comment]
A million periods is the same as 1000 sets of 1000 periods.
