### ISSUE TITLE
Error using spkron when calling for the "SlowsIRFs" or "MedianIRFs" option

### ISSUE THREAD

**Issue by kenghua-huang** [tholden/dynareOBC#41]
My code can work with the default "FastIRFs" option. But when I turn to the "SlowIRFs" or "MedianIRFs" option, it raises the following error:

Error using spkron
An UndefinedFunction error was thrown on the workers for 'spkron_internal_mex_mex'.  This might be because the file
containing 'spkron_internal_mex_mex' is not accessible on the workers. Use addAttachedFiles(pool, files) to specify the
required files to be attached.  For more information, see the documentation for 'parallel.Pool/addAttachedFiles'.

Error in ExpectedReturn (line 14)
            y1s2 = spkron( y1s, y1s );

Error in SimulateModel (line 262)
                    ReturnPathStruct = ExpectedReturn( CurrentStateWithoutBound, M_, oo_.dr, dynareOBC_ );

Error in SlowIRFs (line 50)
    parfor k = 1: Replications

Error in dynareOBCCore (line 669)
                [ oo_, dynareOBC ] = SlowIRFs( M_, oo_, dynareOBC );

![image](https://github.com/tholden/dynareOBC/assets/61227853/98cf469a-16ff-4c61-87cc-81ec05189bd3)

I use the latest dynareOBC release and dynare v4.5.7. How should I proceed to deal with this error?

**Comment by tholden** [comment]
I've not encountered this before. What operating system are you using? What parallel pool are you using?

**Comment by kenghua-huang** [comment]
> I've not encountered this before. What operating system are you using? What parallel pool are you using?

Hi, I use Windows 10 and I only use the default option for parallel pool which means it will automatically create a pool if none exists when keywords like "parfor" is called.

**Comment by tholden** [comment]
Do you have a compiler installed? Paste the output of 'mex - setup" here.

**Comment by kenghua-huang** [comment]
> Do you have a compiler installed? Paste the output of 'mex - setup" here.

MEX configured to use 'MinGW64 Compiler (C)' for C language compilation.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN

**Comment by tholden** [comment]
What folder is DynareOBC installed in? Is it on a network drive? Can you delete the DynareOBC folder and try again? If there's still an error, paste the complete DynareOBC output here.

**Comment by kenghua-huang** [comment]
> What folder is DynareOBC installed in? Is it on a network drive? Can you delete the DynareOBC folder and try again? If there's still an error, paste the complete DynareOBC output here.

Hi, my dynareOBC is installed in a different folder in dynare as your homepage suggests. I tried to delete the folder and reinstall but still not work. The error message is as follows:

------------------------------------------------------------------------------------------------------------------------------

Error using spkron
An UndefinedFunction error was thrown on the workers for 'spkron_internal_mex_mex'.  This might be because the file
containing 'spkron_internal_mex_mex' is not accessible on the workers. Use addAttachedFiles(pool, files) to specify the
required files to be attached.  For more information, see the documentation for 'parallel.Pool/addAttachedFiles'.

Error in ExpectedReturn (line 14)
            y1s2 = spkron( y1s, y1s );

Error in SimulateModel (line 262)
                    ReturnPathStruct = ExpectedReturn( CurrentStateWithoutBound, M_, oo_.dr, dynareOBC_ );

Error in SlowIRFs (line 50)
    parfor k = 1: Replications

Error in dynareOBCCore (line 669)
                [ oo_, dynareOBC ] = SlowIRFs( M_, oo_, dynareOBC );

Error in dynareOBCSetup (line 297)
            dynareOBC_ = dynareOBCCore( InputFileName, basevarargin, dynareOBC_, @() EnforceRequirementsAndGeneratePath(
            Update, OriginalPath, CurrentFolder, dynareOBCPath, InputFileName, varargin{:} ) );

Error in dynareOBC (line 711)
        dynareOBCSetup( OriginalPath, CurrentFolder, dynareOBCPath, InputFileName, varargin{:} );

Error in main (line 57)
dynareOBC MPU_TFPU_sol.mod MILPSolver=mosek cubature SlowIRFs;

Caused by:
    Unrecognized function or variable 'spkron_internal_mex_mex'.

**Comment by tholden** [comment]
No, I need the entire DynareOBC output. The mex file is created early on in the DynareOBC call.

**Comment by kenghua-huang** [comment]
> No, I need the entire DynareOBC output. The mex file is created early on in the DynareOBC call.

Sorry for the misunderstanding. I attach the diary txt file for the complete output here. Is that what you mean?
[dynareOBC.txt](https://github.com/tholden/dynareOBC/files/15457420/dynareOBC.txt)

**Comment by tholden** [comment]
Could you try editing Core/OBCSimulation/SlowIRFs.m and add the line `updateAttachedFiles( gcp );` before the parfor call on line 50, and before the parfor call on line 107.
You should also try running MATLAB with Admin rights, as it seems that not all dependencies are correctly installed.
Your run log also showed some other incompatibilities between the latest Gurobi and the current version of DynareOBC, as well as incompatibilities with the latest MATLAB. I will issue a new DynareOBC fixing these.

**Comment by tholden** [comment]
The new release is here: https://github.com/tholden/dynareOBC/releases/tag/v3.31.55.1974
Please extract it to a clean directory and run your test again.
If it still fails, then could you make the edits to SlowIRFs I mentioned above and let me know if that makes any difference.

**Comment by kenghua-huang** [comment]
> The new release is here: https://github.com/tholden/dynareOBC/releases/tag/v3.31.55.1974 Please extract it to a clean directory and run your test again. If it still fails, then could you make the edits to SlowIRFs I mentioned above and let me know if that makes any difference.

Hi, thanks for the quick reply and the patience. I downloaded the latest release you just provided and also edited the SlowIRFs file, but still get the same error. I attached the new log file here.
[dynareOBC.txt](https://github.com/tholden/dynareOBC/files/15462843/dynareOBC.txt)

**Comment by tholden** [comment]
I don't think I'm able to debug this without actually seeing it on your computer.
Perhaps you'd be prepared to invite me to a TeamViewer session on your PC?

**Comment by kenghua-huang** [comment]
> I don't think I'm able to debug this without actually seeing it on your computer. Perhaps you'd be prepared to invite me to a TeamViewer session on your PC?

Sure. May I know the time zone you are in and your availability this week such that I can find a proper time to set it up? Also, my code changes a bit right now and I'll let you know once I'm prepared. Thanks a lot for the patience!

**Comment by kenghua-huang** [comment]
> I don't think I'm able to debug this without actually seeing it on your computer. Perhaps you'd be prepared to invite me to a TeamViewer session on your PC?

Sorry that I also have another maybe stupid question. How can I achieve the RSS value from the results?

**Comment by tholden** [comment]
I'm in Germany (UTC+2). Afternoons work best for me. Send me an email to my personal address with the TeamViewer details.
I don't know what you mean about "RSS value".

**Comment by kenghua-huang** [comment]
> I'm in Germany (UTC+2). Afternoons work best for me. Send me an email to my personal address with the TeamViewer details. I don't know what you mean about "RSS value".

Sorry for the confusion. I mean the risky steady state value.

**Comment by kenghua-huang** [comment]
> > I don't think I'm able to debug this without actually seeing it on your computer. Perhaps you'd be prepared to invite me to a TeamViewer session on your PC?
> 
> Sure. May I know the time zone you are in and your availability this week such that I can find a proper time to set it up? Also, my code changes a bit right now and I'll let you know once I'm prepared. Thanks a lot for the patience!

Hi, I found the reason of that weird error by accident. It's because I didn't remove the path of the latest version of dynare. Once I removed it, everything works perfectly well now. Thanks again for the patiently guidence!
