### ISSUE TITLE
Cubature error 

### ISSUE THREAD

**Issue by Lauroc** [tholden/dynareOBC#5]
Undefined function or variable 'y'.
Error in PerformCubature (line 132)
            yError = max( abs( y - yNew ) );
Error in FastIRFs>FastIRFsInternal (line 57)
            [ y, GlobalVarianceShare ] = PerformCubature( UnconstrainedReturnPath, oo, dynareOBC, TempIRFStruct.first, false, [ 'Computing
            required integral for fast IRFs for ' ShockName '. Please wait for around ' ], '. Progress: ', [ 'Computing required integral
            for fast IRFs for ' ShockName '. Completed in ' ] );
Error in FastIRFs (line 16)
        y = FastIRFsInternal( Shock, 'the base path', M, oo, dynareOBC );
Error in dynareOBCCore (line 520)
                [ oo_, dynareOBC ] = FastIRFs( M_, oo_, dynareOBC );
Error in dynareOBCSetup (line 161)
        dynareOBC_ = dynareOBCCore( InputFileName, basevarargin, dynareOBC_, @() EnforceRequirementsAndGeneratePath( Update, OriginalPath,
        CurrentFolder, dynareOBCPath, InputFileName, varargin{:} ) );
Error in dynareOBC (line 627)
            end
Error in analysis_ (line 7)
dynareOBC BasicModel3_UI IRFsAroundZero TimeToEscapeBounds=128 shockscale=1 UseVPA PTest=1 compilesimulationcode FeasibilityTestGridSize=1

**Comment by tholden** [comment]
Apologies. That is a genuine bug introduced in the last release. I was testing with CubatureTolerance=0.

To work around, run with the command line option CubatureTolerance=0 . A fix will be out imminently.

**Comment by tholden** [comment]
Thanks again for this. Note that it should be fixed in this release: https://github.com/tholden/dynareOBC/releases/tag/v2.60.1593

Let me know if you have any further problems.

**Comment by Lauroc** [comment]
Thank you!
