### ISSUE TITLE
Error with mosekopt

### ISSUE THREAD

**Issue by ChenxiWang1234** [tholden/dynareOBC#8]
Dear Professor Holden,

I updated to the latest release and tested it using one of your examples. However, I received the following message: 

"Error using InitialChecks (line 522)
This should never happen. Double-check your DynareOBC install, or try a different solver.
Internal error message: Unknown problem in solver (Turn on 'debug' in sdpsettings)
(Undefined function 'mosekopt' for input arguments of type 'struct'.)"

I checked the source code but cannot find the "mosekopt.m" function. Could you help me with this issue? Thank you very much!

Chenxi

**Comment by tholden** [comment]
This is related to a bug in YALMIP: https://github.com/yalmip/YALMIP/issues/502
Until I make a new release, you can work around this issue by downloading the latest YALMIP from the "develop" brach here https://github.com/yalmip/YALMIP/archive/develop.zip, then copying its contents over the YALMIP copy within the Extern sub folder of DynareOBC.

**Comment by tholden** [comment]
This should be fixed in the latest release, available from: https://github.com/tholden/dynareOBC/releases/tag/v2.80.1639
