### ISSUE TITLE
Does dynareOBC work with uncertainty shocks (shocks to second order moments)?

### ISSUE THREAD

**Issue by mishuaashu** [tholden/dynareOBC#9]
Dear Holden,

First of all I would like to thank you for your dynareOBC contribution. It is so simple to work with OBCs using dynareOBC. 

My query is following,

Is it possible to simulate the results for a model with uncertainty shocks and  ZLB using dynareOBC? Everytime I run the mod file I get "DynareOBC failed to find a solution to the model." Although the model seems to work fine without ZLB, using dynare command.

Here is a simple one sector NK model, I tried to work with, 
[test.log](https://github.com/tholden/dynareOBC/files/2480748/test.log)

Any help in this regard would be very helpful to me.

Thanks & regards.

**Comment by tholden** [comment]
This is a model in which although the constraint is slack at the non-stochastic steady-state, it binds at the risky steady-state. But at the risky steady-state, the model is indeterminate. You have three choices. 1) Reduce the standard deviations of shocks. 2) Increase the steady-state level of inflation until the constraint no longer binds at the steady-state. At the moment you seem to have an implausibly low level. 3) Explicitly solve round the deflationary steady-state, "fixing" the indeterminacy following the approach of https://ideas.repec.org/a/eee/dyncon/v54y2015icp17-36.html

**Comment by mishuaashu** [comment]
Thanks Holden. I will look into your suggestions.

Regards,
Sargam
---------------------
Sargam Gupta
Senior Research Fellow (SRF)
Indian Statistical Institute, Delhi
Website: https://sites.google.com/site/sargamgupta6/
